  
name: TestGit

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - run: |
        git config --global user.email "jodu035@gmail.com"
        git config --global user.name "FaustVX"
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1.0.2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - run: |
        nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/FaustVX/index.json" -UserName FaustVX -Password ${{ secrets.TOKEN }}
        nuget setApiKey ${{ secrets.TOKEN }} -source "GitHub"
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
        java-package: jdk
        architecture: x64
    - name: build
      run: dotnet build
    - name: test
      run: dotnet test
    - name: Execute program (Debug)
      working-directory: ./MinecraftVersionDownloader.App
      run: dotnet run -c Debug -v q https://${{ secrets.TOKEN }}@github.com/FaustVX/MinecraftVanillaDatapack.git
    - name: Execute program (Release)
      working-directory: ./MinecraftVersionDownloader.App
      run: dotnet run -c Release -v q https://${{ secrets.TOKEN }}@github.com/FaustVX/MinecraftVanillaDatapack.git --long-run

