  
name: UploadToMCVanillaRepo

on:
  push:
    paths: .github/workflows/**
  schedule:
  - cron: '*/30 15-20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - run: git clone https://${{ secrets.TOKEN }}@github.com/FaustVX/MinecraftVanillaDatapack.git
    - run: git clone https://${{ secrets.TOKEN }}@github.com/FaustVX/MinecraftVersionDownloader.git
    - uses: actions/setup-dotnet@v1.0.2
      with:
        dotnet-version: '3.0.100'
    - name: Build program
      run: |
        cd ./MinecraftVersionDownloader/MinecraftVersionDownloader.App
        dotnet build -c Release
    - name: Execute program
      run: |
        cd ./MinecraftVersionDownloader/MinecraftVersionDownloader.App
        dotnet run -c Release -v q ../../MinecraftVanillaDatapack assets data pack. version.json
